In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size=10000

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[611, 1846, 5886, 7918],
 [611, 1846, 5886, 9457],
 [611, 3083, 5886, 2992],
 [2451, 4168, 8377, 6317, 8374],
 [2451, 4168, 8377, 6317, 2479],
 [1302, 611, 8431, 5886, 2502],
 [5925, 3474, 4900, 6317]]

In [24]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [26]:
sent_length=6
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0  611 1846 5886 7918]
 [   0    0  611 1846 5886 9457]
 [   0    0  611 3083 5886 2992]
 [   0 2451 4168 8377 6317 8374]
 [   0 2451 4168 8377 6317 2479]
 [   0 1302  611 8431 5886 2502]
 [   0    0 5925 3474 4900 6317]]


In [27]:
## feature representation
dim=10

In [28]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [29]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step


array([[[-1.9698083e-02, -3.0609537e-02,  4.7352914e-02, -3.9772414e-02,
         -4.0109407e-02,  3.4831170e-02,  2.3333017e-02,  3.6526393e-02,
          1.0727931e-02,  4.7397915e-02],
        [-1.9698083e-02, -3.0609537e-02,  4.7352914e-02, -3.9772414e-02,
         -4.0109407e-02,  3.4831170e-02,  2.3333017e-02,  3.6526393e-02,
          1.0727931e-02,  4.7397915e-02],
        [-4.2030167e-02, -5.0734766e-03, -3.6660545e-03,  5.8372840e-03,
          8.6244121e-03, -2.2658909e-02, -4.3034375e-02,  9.3858354e-03,
          3.6370385e-02, -4.1113198e-02],
        [-3.3739761e-02, -3.4405150e-02, -1.9013179e-02, -4.4261374e-02,
          3.0252967e-02,  2.6310671e-02,  1.3836969e-02, -3.4570169e-02,
         -9.0618059e-04,  4.1337777e-02],
        [ 3.6261085e-02,  2.8743301e-02,  3.3191297e-02,  3.1919692e-02,
         -3.6382031e-02,  1.3899494e-02,  3.6067549e-02,  2.3451004e-02,
         -2.2067083e-02, -8.0371387e-03],
        [-1.7037272e-02, -8.7334290e-03, -3.2480553e-02,  1.

In [31]:
embedded_docs[0]

array([   0,    0,  611, 1846, 5886, 7918])

In [36]:
model.predict(embedded_docs[0][0])

IndexError: tuple index out of range